- job:
    name: patrole-base
    parent: legacy-dsvm-base
    timeout: 7800
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*
      - ^patrole/patrole_tempest_plugin/tests/unit/.*$
      - ^releasenotes/.*
      - ^setup.cfg$
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/patrole
      - openstack/tempest

- job:
    name: patrole-base-multinode
    parent: legacy-dsvm-base-multinode
    timeout: 7800
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^doc/.*
      - ^patrole/patrole_tempest_plugin/tests/unit/.*$
      - ^releasenotes/.*
      - ^setup.cfg$
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/patrole
      - openstack/tempest

- job:
    name: patrole-admin
    parent: patrole-base
    run: playbooks/legacy/patrole-admin/run.yaml
    post-run: playbooks/legacy/patrole-admin/post.yaml

- job:
    name: patrole-member
    parent: patrole-base
    run: playbooks/legacy/patrole-member/run.yaml
    post-run: playbooks/legacy/patrole-member/post.yaml

- job:
    name: patrole-multinode-admin
    parent: patrole-base-multinode
    run: playbooks/legacy/patrole-multinode-admin/run.yaml
    post-run: playbooks/legacy/patrole-multinode-admin/post.yaml
    voting: false
    nodeset: legacy-ubuntu-xenial-2-node

- job:
    name: patrole-multinode-member
    parent: patrole-base-multinode
    run: playbooks/legacy/patrole-multinode-member/run.yaml
    post-run: playbooks/legacy/patrole-multinode-member/post.yaml
    voting: false
    nodeset: legacy-ubuntu-xenial-2-node

- job:
    name: patrole-py35-member
    parent: patrole-base
    run: playbooks/legacy/patrole-py35-member/run.yaml
    post-run: playbooks/legacy/patrole-py35-member/post.yaml

- project:
    check:
      jobs:
        - patrole-admin
        - patrole-member
        - patrole-py35-member
        - patrole-multinode-admin
        - patrole-multinode-member
    gate:
      jobs:
        - patrole-admin
        - patrole-member
        - patrole-py35-member
